config/routes.rb
Rails.application.routes.draw do

  get "session/new"
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/home", to: "static_pages#home"
  get "/contact", to: "static_pages#contact"
  get "/about", to: "static_pages#about"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  get "/about", to: "static_pages#about"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_toke
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: Settings.size_name}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.size_email},
  format: {with: VALID_EMAIL_REGEX},
  uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: Settings.size_pass}
  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end
  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  def forget
    update_attribute :remember_digest, nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = t "notipass"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
     @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "user_controller"
      log_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find_by id: params[:id]
    return if @user
    flash[:error] = t "not_found"
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/session_helper.rb
module SessionHelper

  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end
  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for user, options ={size: Settings.size_userhelper}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <%= link_to "Ruby on Rails Tutorial", "http://www.railstutorial.org/" %>
    by <%= link_to "Michael Hartl", "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("about"),   "#" %></li>
      <li><%= link_to t("contact"), "#" %></li>
      <li><%= link_to t("news"), "http://news.railstutorial.org/"%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-dark bg-dark">
  <div class="container">
    <%= link_to "sample app", home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right lider">
        <li><%= link_to t("l-home"), home_path %></li>
        <li><%= link_to t("l-help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users"), "#" %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", id: "dropdownMenuButton",data: {toggle: "dropdown"} do%>
              <%= t "account" %><b class="caret"></b>
            <% end %>
            <!-- <a class="dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a> -->
            <ul class="dropdown-menu" id="menu" aria-labelledby="dropdownMenuButton">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
         <li><%= link_to t("l-log"), login_path %></li>
        <% end %>
      </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
  <%= render "layouts/header.html.erb" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    	<%= yield %>
      <%= render "layouts/footer.html.erb" %>
    </div>
  </body>
</html>

app/views/session/new.html.erb
<% provide :title, t("log_in") %>
<h1><%= t "session.new.log_in" %></h1>
<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span><%= t "session.new.computer_me" %></span>
      <% end %>
      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>
    <p>New user? <%= link_to t("sign_up"), signup_path %></p>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
    <%= t "form-containt", pluralize(@user.errors.count, "error") %>.
  </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1><%= t "help" %></h1>
<p><%= t "back" %> <%= link_to "home", "home" %></p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t "wellcome"%></h1>
  <h2>
    <%= t "home_page" %>
    <%= link_to t("rails-call"), "http://www.railstutorial.org/" %>
    sample application.
  </h2>
  <%= link_to t("sign_up"), new_user_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), "http://rubyonrails.org/" %>

app/views/users/edit.html.erb
<% provide :title, t("Edit_user") %>
<h1><%= t "update" %></h1>
<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t "confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("save"), class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t("change"), "http://gravatar.com/emails" , target: "blank" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t("user_new") %>
<h1><%= t "user_new" %></h1>
<div class="row justify-content-md-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, t("confer") %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit t("create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>